# Generated by Django 5.0.6 on 2024-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_planning_age_business_planning_age_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='investment',
            name='risk_tolerance',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=12),
        ),
    ]
